Format all web code
OpenStickCommunity/GP2040-CE pull request #436
Opened 2023-07-30 19:23 UTC by Pelsin

No changes in code/functionality except the .editorconfig.
This is purely for developer experience.

Ran prettier to format the files in the www folder.
`npx prettier --write "{www/src,www/server}/**/*.{tsx,ts,jsx,js,json,scss}"`

Changed .editorconfig to handle EOL as lf, so it matches .gitattributes

2023-08-07 01:58 UTC, SavageCore requested changes
I'd prefer `singleQuote`: `true` but otherwise, very nice and very welcome!

Should we add [husky](https://github.com/typicode/husky) to enforce linting on commit? 

`lint` script should be added to the `package.json` and we should then extend `node.js.yml` action to run lint tests.

2023-08-07 17:37 UTC, Pelsin commented
> I'd prefer `singleQuote`: `true` but otherwise, very nice and very welcome!
True, i also prefer single quotes. I've changing it in editorconfig for js/ts files. Will check with the other if someone objects :)

> Should we add [husky](https://github.com/typicode/husky) to enforce linting on commit?
> `lint` script should be added to the `package.json` and we should then extend `node.js.yml` action to run lint tests.

Sounds like a great idea, had a short discussion with feralAi about the linting when we moved from CRA to vite.
There currently is a lint script in package.json, there are some errors that we wanted to clean up before making linting part of the pipeline.
Husky and adding to pipeline feels like a really nice next step, in another branch thought!

Thanks for checking the PR out @SavageCore!

2023-08-07 17:56 UTC, SavageCore approved these changes

2023-08-16 16:42 UTC, arntsonl approved these changes
Looks awesome!

2023-08-16 16:42 UTC, merged