feat: Enable Tilt Value Configuration via WebConfig
OpenStickCommunity/GP2040-CE pull request #500
Opened 2023-09-05 12:21 UTC by smashBrosKanu

### Overview
This pull request adds the ability to configure the Tilt value through WebConfig.

### Background
Different characters may require unique Tilt values to perform their intended actions. Given this, it is desirable to allow users to set these values themselves.

### Usage
Users can now freely set the Tilt value through the WebConfig settings interface.

### Impact
This change affects the WebConfig UI and the logic that processes the Tilt value.

### Testing
Manual testing was conducted in a local environment to ensure that the Tilt value could be accurately set.

Please review. Thank you!

2023-09-05 12:24 UTC, TheTrainGoes commented
Looks neat!  I will check this out today when I have some time

2023-09-05 15:58 UTC, Pelsin commented on www/src/Locales/zh-CN/AddonsConfig.jsx
> +	'tilt-2-factor-right-y-label': 'Tilt 2 Factor Right Y',
Same here

2023-09-08 19:29 UTC, mthiesen requested changes

2023-09-08 19:29 UTC, mthiesen commented on proto/config.proto
> +	optional int32 factorTilt1LeftX =  3;
You should never change the tag numbers of existing protobuf fields, this breaks backwards compatibility. You can add as many new fields as you like, and you can change the order of the fields in a struct as long as the tag numbers of existing fields do not change.

2023-09-15 14:47 UTC, arntsonl approved these changes
Looks good!

2023-09-15 14:47 UTC, merged