show profile number on display
OpenStickCommunity/GP2040-CE pull request #689
Opened 2023-12-21 16:56 UTC by hitsmaxft

1. implementation of issue #688  show current profile number in display
2. append current firmware version in save filename

2023-12-27 03:54 UTC, mikepparks commented
A few things of note here:
* Screen width is 21 characters wide. By adding "#n" after directional mode, the "macro" mode display is now being shifted off the screen by 1.
* Try not to mix contexts in your PRs. This should be two separate PRs since they're unrelated issues.

Please split the PRs into two, and consider another direction to display of profile number that doesn't impact the current status text.

2023-12-27 15:01 UTC, hitsmaxft commented
> A few things of note here:
> 
>     * Screen width is 21 characters wide. By adding "#n" after directional mode, the "macro" mode display is now being shifted off the screen by 1.
> 
>     * Try not to mix contexts in your PRs. This should be two separate PRs since they're unrelated issues.
> 
> 
> Please split the PRs into two, and consider another direction to display of profile number that doesn't impact the current status text.

i've remove backup file changes . 
about the text width , can i add a new option to  display config , to control this feature

2023-12-29 21:49 UTC, arntsonl requested changes

2023-12-29 21:49 UTC, arntsonl commented on src/addons/i2cdisplay.cpp
For this one, we will want a conditional for Macros since the 'M' will take the last character place. Once you add that, we can merge thank you!

2023-12-31 04:27 UTC, hitsmaxft commented on src/addons/i2cdisplay.cpp
I've moved the profile number to last of status text and  make it disappear if profile number is 1 or macro enabled 
I think every work is done,  improvements would in next PR

2023-12-31 21:30 UTC, arntsonl commented
We have a major display rewrite coming soon so we're going to request a new PR once that has been completed. Lots of movement and dev on this thing right now, so we'll probably have a few conflicts like this that are not on the main branch.

@hitsmaxft once the display rewrite is done, we can look into displaying profile numbers!

2023-12-31 21:30 UTC, closed without merging