Add Reflex CTRL Genesis-6, NES, Saturn, and Virtual Boy
OpenStickCommunity/GP2040-CE pull request #982
Opened 2024-04-20 07:25 UTC by misteraddons

Drop-in USB conversions for classic controllers.

2024-04-21 15:18 UTC, TheTrainGoes commented on configs/ReflexCtrlNES/BoardConfig.h
> +// Input Mode additions section.
To keep with the cleanup efforts in board-configs previously, all of the // lines except the top Licence and FireCopyrightText ones can be removed.

2024-04-21 15:19 UTC, TheTrainGoes requested changes
Looking good.  Left a comment for you about removing the commented out lines.  We did a big cleanup to remove unneeded lines a while back.

2024-04-21 17:09 UTC, misteraddons commented
Commented lines removed. Thanks!

2024-04-22 19:35 UTC, arntsonl approved these changes
Looks good, comments were removed and folders look good to me!

2024-04-22 19:38 UTC, merged